#!/usr/bin/env bash
echo '      ____              __        '
echo '     / __ \   ____ _   / /      ___ '
echo '    / / / /  / __ `/  / /      / _ \'
echo '   / /_/ /  / /_/ /  / /___   /  __/'
echo '  /_____/   \__,_/  /_____/   \___/ '
echo ''
echo '    +-+-+-+-+-+-+-+-+-+-+ +-+-+-+'
echo '    |L|i|n|u|x|s|h|e|l|l| |C|L|I|'
echo '    +-+-+-+-+-+-+-+-+-+-+ +-+-+-+'
echo ''
echo '  >> Author : David Lejeune'
echo "  >> Created : 24/08/2017"
echo ''
echo ' ###################################'
echo ' #     REMOTE AGENT SETUP LINUX    #'
echo ' ###################################'
echo ''

echo 'Making sure the system is up-to-date'
sudo apt-get update
sudo apt-get upgrade

echo ""
echo "--------------------------------------------------------------"
echo " INSTALLING ANT"
echo "--------------------------------------------------------------"
sudo apt-get install ant
echo $ANT_HOME
if [ ${#ANT_HOME} -le 1 ]; then
	echo "ANT_HOME not found" ;
	read -r -p "Would you like to add the ANT_HOME enviroment variable? [y/N] " response
	if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
	then
		echo "export ANT_HOME=/usr/bin/ant" | sudo tee --append /etc/profile
		echo "export PATH=$ANT_HOME:$PATH" | sudo tee --append /etc/profile
	else
			echo "Please do this manually !!! "
	fi

else
	echo "ANT_HOME exists already"
fi

sleep 3



echo "--------------------------------------------------------------"
echo " INSTALLING GIT"
echo "--------------------------------------------------------------"
sudo apt-get install git

echo "--------------------------------------------------------------"
echo " INSTALLING OPENSSH-SERVER"
echo "--------------------------------------------------------------"
sudo apt-get install openssh-server



echo "--------------------------------------------------------------"
echo " INSTALLING JDK"
echo "--------------------------------------------------------------"
echo "See git repo oraclejdk-arm"
# sudo apt-get install openjdk-8-jre-headless
# echo $JAVA_HOME
# if [ ${#JAVA_HOME} -le 1 ]; then
# 	echo "JAVA_HOME not found" ;
# 	echo "export JAVA_HOME=/usr/bin/java" | sudo tee --append /etc/profile
# 	echo "export PATH=$JAVA_HOME/bin:$PATH" | sudo tee --append /etc/profile
#
# else
# 	echo "JAVA_HOME exists already"
# fi
sudo apt-get update
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
sudo apt-get install oracle-java8-installer -y
# #manually accept the license agreement
sudo echo 'JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"' >> /etc/environment
sudo update-alternatives --config javac
sudo update-alternatives --config java

#git clone git@github.com:DavidLejeune/oraclejavajdk-arm.git
#chmod u+x ./oraclejavajdk-arm/install-jdk-arm
#./oraclejavajdk-arm/install-jdk-arm


echo "--------------------------------------------------------------"
echo " INSTALLING FUN STUFF"
echo "--------------------------------------------------------------"
sudo apt-get install toilet
sudo apt-get install figlet
sudo apt-get install fortune

echo "--------------------------------------------------------------"
echo " INSTALLING NPM , GULP and NODE"
echo "--------------------------------------------------------------"
sudo apt-get install npm
sudo npm install -g gulp
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh | bash
sudo apt-get install -y nodejs



echo "--------------------------------------------------------------"
echo " GIVING THIS SERVER A FIXED IP"
echo "--------------------------------------------------------------"
echo "Ensure that you have 3 interfaces"
echo ">>netw 1 NAT"
echo ">>netw 2 Bridged"
echo ">>netw 3 Host only "

read -r -p "What is the fixed ip address to use for this VM ? " ip
if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then

# CN=`echo $ip | cut -d . -f 4`
# sudo echo $'allow-hotplug enp0s8\n' | sudo tee -a /etc/network/interfaces
# # sudo echo $'iface enp0s8 inet static\n' | sudo tee -a /etc/network/interfaces
# sudo echo $'iface enp0s8 inet dhcp\n' | sudo tee -a /etc/network/interfaces
# sudo echo "address 192.168.56."$CN$'\n' | sudo tee -a /etc/network/interfaces
# sudo echo $'netmask 255.255.254.0\n' | sudo tee -a /etc/network/interfaces
#
# sudo echo $'allow-hotplug enp0s9\n' | sudo tee -a /etc/network/interfaces
# sudo echo $'iface enp0s9 inet static\n' | sudo tee -a /etc/network/interfaces
# sudo echo "address "$ip$'\n' | sudo tee -a /etc/network/interfaces
# sudo echo $'netmask 255.255.254.0\n' | sudo tee -a /etc/network/interfaces
# else
#   echo "That isn't a valid ip numbnuts."
# fi


echo "--------------------------------------------------------------"
echo " RUNNING BAMBOO JVM"
echo "--------------------------------------------------------------"
url="http://84.199.251.203/agentServer/agentInstaller/atlassian-bamboo-agent-installer-6.0.2.jar"
rm -f atlassian-bamboo-agent-installer-6.0.2.jar
wget $url

#java -Dbamboo.Home=/home/pi/bamboo-agent-home -jar atlassian-bamboo-agent-installer-6.0.2.jar http://84.199.251.203/agentServer/
#java -jar atlassian-bamboo-agent-installer-6.0.2.jar http://84.199.251.203/agentServer/

mkdir ~/bamboo-agent-home
cp atlassian-bamboo-agent-installer-6.0.2.jar ~/bamboo-agent-home
cp launch_remote ~/bamboo-agent-home
chmod u+x ~/bamboo-agent-home/launch_remote
read -r -p "Would you like to run the bamboo remote agent VM now? [y/N] " response
	if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
	then
			~/bamboo-agent-home/launch_remote
	else
			echo "Run the launch-remote script from bamboo-agent-home manually then you filthy peasant "
	fi
