#!/usr/bin/env bash
Echo '      ____              __        '
Echo '     / __ \   ____ _   / /      ___ '
Echo '    / / / /  / __ `/  / /      / _ \'
Echo '   / /_/ /  / /_/ /  / /___   /  __/'
Echo '  /_____/   \__,_/  /_____/   \___/ '
Echo ''
Echo '    +-+-+-+-+-+-+-+-+-+-+ +-+-+-+'
Echo '    |L|i|n|u|x|s|h|e|l|l| |C|L|I|'
Echo '    +-+-+-+-+-+-+-+-+-+-+ +-+-+-+'
Echo ''
Echo '  >> Author : David Lejeune'
Echo "  >> Created : 24/08/2017"
Echo ''
Echo ' ###################################'
Echo ' #     REMOTE AGENT SETUP LINUX    #'
Echo ' ###################################'
Echo ''


Echo "--------------------------------------------------------------"
Echo " INSTALLING GIT"
Echo "--------------------------------------------------------------"
sudo apt-get install git


Echo "--------------------------------------------------------------"
Echo " INSTALLING JDK"
Echo "--------------------------------------------------------------"
sudo apt-get install openjdk-8-jre-headless
echo $JAVA_HOME
if [ ${#JAVA_HOME} -le 1 ]; then
	echo "JAVA_HOME not found" ;
	echo "export JAVA_HOME=/usr/bin/java" | sudo tee --append /etc/profile
	echo "export PATH=$JAVA_HOME/bin:$PATH" | sudo tee --append /etc/profile

else
	echo "JAVA_HOME exists already"
fi


Echo "--------------------------------------------------------------"
Echo " INSTALLING ANT"
Echo "--------------------------------------------------------------"
sudo apt-get install ant
echo $ANT_HOME
if [ ${#ANT_HOME} -le 1 ]; then
	echo "ANT_HOME not found" ;
	echo "export ANT_HOME=/usr/bin/ant" | sudo tee --append /etc/profile
	echo "export PATH=$ANT_HOME:$PATH" | sudo tee --append /etc/profile

else
	echo "ANT_HOME exists already"
fi


Echo "--------------------------------------------------------------"
Echo " RUNNING BAMBOO JVM"
Echo "--------------------------------------------------------------"
url="http://84.199.251.203/agentServer/agentInstaller/atlassian-bamboo-agent-installer-6.0.2.jar"
rm -f atlassian-bamboo-agent-installer-6.0.2.jar
wget $url
java -jar atlassian-bamboo-agent-installer-6.0.2.jar http://84.199.251.203/agentServer/
